name: security

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  dependency-and-secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Run pip-audit (requirements)
        run: |
          if [ -f requirements.txt ]; then pip-audit -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip-audit -r requirements-dev.txt || true; fi

      - name: Secrets scan (gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --no-banner


